### ISSUE TITLE
Another approach to expose application

### ISSUE THREAD

**Issue by chenjiandongx** [draveness/proxier#13]
@draveness 

Inspired by your great idea, I try to take another approach to expose application. 

[chenjiandongx/kslb](https://github.com/chenjiandongx/kslb) is still under development, but it can bring me all basic satisfactions.✌️

**Comment by draveness** [comment]
So what's your point to create an issue here? You could add inspired by `proxier` in `README.md`...

**Comment by chenjiandongx** [comment]
@draveness 

Thanks for your idea.
